NAME = "hypertune"
VERSION = "1.1.0-rc42"
DESC = "A library for performing hyperparameter optimization with Polyaxon."
URL = "https://github.com/polyaxon/hypertune"
AUTHOR = "Polyaxon, Inc."
EMAIL = "contact@polyaxon.com"
LICENSE = "Apache 2.0"
